[package]
name = "complex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl_ops = "0.1.1"
regex = "1.9.5"
thiserror = "1.0.49"
lazy_static = "1.4.0"
